# Generated by Django 5.2 on 2025-04-15 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("billing", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="patient",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "patient"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Patient",
            ),
        ),
        migrations.AddField(
            model_name="insuranceclaim",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="insurance_claims",
                to="billing.invoice",
                verbose_name="Invoice",
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="billing.invoice",
                verbose_name="Invoice",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="billing.invoice",
                verbose_name="Invoice",
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_items",
                to="billing.service",
                verbose_name="Service",
            ),
        ),
    ]
