# Generated by Django 5.2 on 2025-04-17 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ehr", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalrecord",
            name="doctor",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "doctor"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_medical_records",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Doctor",
            ),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="patient",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "patient"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medical_records",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Patient",
            ),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="medical_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diagnoses",
                to="ehr.medicalrecord",
                verbose_name="Medical Record",
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="medical_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescriptions",
                to="ehr.medicalrecord",
                verbose_name="Medical Record",
            ),
        ),
        migrations.AddField(
            model_name="treatment",
            name="medical_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="treatments",
                to="ehr.medicalrecord",
                verbose_name="Medical Record",
            ),
        ),
    ]
