apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: web
        env:
        - name: DEBUG
          value: "0"
        - name: ENVIRONMENT
          value: "production"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        readinessProbe:
          initialDelaySeconds: 15
          periodSeconds: 5
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 10