# Generated by Django 5.2 on 2025-04-17 11:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="This field is automatically determined by the system, do not interfere.",
                        unique=True,
                        verbose_name="Unique ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Contact Name")),
                (
                    "relationship",
                    models.CharField(max_length=50, verbose_name="Relationship"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=15, verbose_name="Phone Number"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("address", models.TextField(blank=True, verbose_name="Address")),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, verbose_name="Is Primary Contact"
                    ),
                ),
            ],
            options={
                "verbose_name": "Emergency Contact",
                "verbose_name_plural": "Emergency Contacts",
            },
        ),
        migrations.CreateModel(
            name="Insurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="This field is automatically determined by the system, do not interfere.",
                        unique=True,
                        verbose_name="Unique ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(max_length=255, verbose_name="Insurance Provider"),
                ),
                (
                    "policy_number",
                    models.CharField(max_length=50, verbose_name="Policy Number"),
                ),
                (
                    "group_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Group Number"
                    ),
                ),
                (
                    "coverage_start_date",
                    models.DateField(verbose_name="Coverage Start Date"),
                ),
                (
                    "coverage_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Coverage End Date"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "Insurance",
                "verbose_name_plural": "Insurance Policies",
            },
        ),
        migrations.CreateModel(
            name="PatientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="This field is automatically determined by the system, do not interfere.",
                        unique=True,
                        verbose_name="Unique ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")],
                        max_length=10,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=3,
                        null=True,
                        verbose_name="Blood Type",
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Height (cm)",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Weight (kg)",
                    ),
                ),
                ("allergies", models.TextField(blank=True, verbose_name="Allergies")),
                (
                    "chronic_conditions",
                    models.TextField(blank=True, verbose_name="Chronic Conditions"),
                ),
            ],
            options={
                "verbose_name": "Patient Profile",
                "verbose_name_plural": "Patient Profiles",
            },
        ),
    ]
