apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  database-url: cG9zdGdyZXM6Ly9wb3N0Z3Jlczpwb3N0Z3JlcyQxMjNAcG9zdGdyZXM6NTQzMi9oZWFsdGhjYXJlX2Ri  # Replace with your actual base64-encoded database URL
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  secret-key: ZGphbmdvLWludmFsaWQtc2VjcmV0LWtleS1wbGVhc2UtY2hhbmdlLW1l  # Replace with your actual base64-encoded secret key