global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'healthcare-web'
    static_configs:
      - targets: ['healthcare-web:8000']
    metrics_path: '/metrics/'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
