apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: healthcare-dev

patches:
- path: patches/deployment.yaml
- path: patches/service.yaml

configMapGenerator:
- name: app-config
  literals:
  - DEBUG=1
  - ENVIRONMENT=development

secretGenerator:
- name: db-secrets
  literals:
  - database-name=healthcare_dev
  - database-user=postgres
  - database-password=postgres
  - database-url=postgres://postgres:postgres@db:5432/healthcare_dev
- name: app-secrets
  literals:
  - secret-key=dev-secret-key